on:
  push:
  schedule:
    - cron: "*/59 * * * *"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: treebeardtech/treebeard
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          notebooks: "run_on_schedule.ipynb"
