on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: alex-treebeard/treebeard-action@49b18b63581068ada89ca6941cb99545be132129
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
