on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: treebeardtech/treebeard-action@7e6a1f509771fc36bf5b88f5dc2869782f4fe627
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
