name: Health Check

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - master

jobs:
  Run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Treebeard
        run: |
          pip install treebeard
      - name: Set Config
        run: ${{ secrets.TREEBEARD_CONFIGURE_CMD }}
      - name: Run Test
        run: |
          treebeard run -n run_on_schedule.ipynb --watch --confirm
